### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by stuartmccoll** [LandRegistry/common-dev-env#13]
The spatial Postgres example link in the `README.md` is broken - it's pointing at a `.sql` extension, but the extension of the actual file is `.yml`. I've fixed this on a local branch, can push it up with repo access.

**Comment by lendmeapound** [comment]
Merge requests are accepted :)

**Comment by stuartmccoll** [comment]
```
ERROR: Permission to LandRegistry/common-dev-env.git denied to stuartmccoll.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

😭

**Comment by sdchapman** [comment]
Actually it looks like the file extension _should_ be .sql, so the README is right, the filename itself is wrong

**Comment by sdchapman** [comment]
In 1.0.2
