### ISSUE TITLE
Files created in a container are owned by root user on host filesystem

### ISSUE THREAD

**Issue by andymantell** [LandRegistry/common-dev-env#37]
* **I'm submitting a ...**

  * [x] bug report
  * [ ] feature request
  * [ ] support request

(Debatable!?)

* **What is the current behavior?**
Files written inside the container arrive on the host file system owned by the root user. 

* **If the current behavior is a bug, what are the steps to reproduce?**
`bashin` to a container. Use `touch` to create a new file. Navigate to directory on host filesystem and observe that files are owned by root.

* **What is the expected/proposed behavior?**
Files should be written as my current user, not root.

* **What is the motivation / use case for changing the behavior?**
If you want to remove files that were created in the container you have to `sudo rm` them. Causes problems particularly with the flask-skeleton-ui which runs the build script in the container.

* **Please tell us about your environment:**

  * Common-dev-env version: 1.0.5
  * Operating system (and shell, if not the OS default): Ubuntu 18.10 + Zsh
  * Ruby version: 2.5.1p57
 
* **Any other information _(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, etc)_:**
Run docker with the `-u` flag to specify the current user instead of root

**Comment by andymantell** [comment]
Seems like `docker-compose up` doesn't have a corresponding `--user` flag. Am keeping investigating but what I thought would be a simple fix, now isn't...

**Comment by andymantell** [comment]
See https://github.com/moby/moby/issues/22415 and https://github.com/docker/compose/issues/1532

**Comment by sdchapman** [comment]
Users and user file permissions are a very tricky thing get get consistently right for everyone in Docker, as you found in your PR! So just running the containers as a random non-root user has other consequences :/
