### ISSUE TITLE
Non-docker apps

### ISSUE THREAD

**Issue by sdchapman** [LandRegistry/common-dev-env#65]
* **I'm submitting a ...**

  * [x] feature request

* **What is the current behavior?**
  If an "app" is cloned down that does not contain a docker compose file, an error occurs, but this may actually be a legit situation e.g. repo file useful files in it

* **What is the expected/proposed behavior?**
  Allow the dev env config to specify that a given repo does not container a dockerable app

* **What is the motivation / use case for changing the behavior?**
  More flexibility to provide every resource a developer needs

**Comment by ptrelease** [comment]
Yes, we had this problem with a documentation repo - which had no docker compose fragment file.  

The message provided - ''Applications have a mix of docker compose fragments versions. Unable to proceed.' was a bit misleading - as all applications, with docker compose fragments, had version 2.

**Comment by sdchapman** [comment]
A workaround is to provide empty docker compose fragment files, with just a single line specifying the version (2 or 3.7 respectively)
